// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {RCFileType} {Win32\Debug\Project1_DRC.rc}

{$R 'Unit1.dfm' 'Form1:TForm'}
{$R 'Unit2.dfm' 'Form2:TForm'}
{$R 'Unit3.dfm' 'Form3:TForm'}
{$R 'Win32\Debug\Project1_DRC.res' 'Win32\Debug\Project1_DRC.rc'}

{$E KOR}

begin
end.
